# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

TC = float(input("Informe a temperatura em ºC: "))
TF = ((TC*(9/5))+32)

print('A temperatura de {} ºC corresponde a {} ºF!'.format(TC, TF))